name: Build & Test

on: [push, pull_request, workflow_dispatch]
jobs:
  nix:
    strategy:
      matrix:
        package:
          - hyprutils
          - hyprutils-with-tests

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v26
    - uses: DeterminateSystems/magic-nix-cache-action@main

    # not needed (yet)
    # - uses: cachix/cachix-action@v12
    #   with:
    #     name: hyprland
    #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build & Test
      run: nix build .#${{ matrix.package }} --print-build-logs

